
services:
  flask_app:
    build:
      context: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_PATH=/app/furniture_shop.db # path to the database
    volumes:
      - sqlite_data:/app # connect to save the database data

volumes:
  sqlite_data: # database volume
