version: '3.8'

services:

  flask_app:
    build:
      context: .
    container_name: flask_app
    ports:
      - "5000:5000" # Flask app
    environment:
      - FLASK_ENV=production
      - DATABASE_PATH=/app/furniture_shop.db
    volumes:
      - sqlite_data:/app

volumes:
  jenkins_home: {}
  sqlite_data: {}
